// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Configer is an autogenerated mock type for the Configer type
type Configer struct {
	mock.Mock
}

type Configer_Expecter struct {
	mock *mock.Mock
}

func (_m *Configer) EXPECT() *Configer_Expecter {
	return &Configer_Expecter{mock: &_m.Mock}
}

// GetAddressAccrual provides a mock function with given fields:
func (_m *Configer) GetAddressAccrual() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Configer_GetAddressAccrual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAddressAccrual'
type Configer_GetAddressAccrual_Call struct {
	*mock.Call
}

// GetAddressAccrual is a helper method to define mock.On call
func (_e *Configer_Expecter) GetAddressAccrual() *Configer_GetAddressAccrual_Call {
	return &Configer_GetAddressAccrual_Call{Call: _e.mock.On("GetAddressAccrual")}
}

func (_c *Configer_GetAddressAccrual_Call) Run(run func()) *Configer_GetAddressAccrual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Configer_GetAddressAccrual_Call) Return(_a0 string) *Configer_GetAddressAccrual_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Configer_GetAddressAccrual_Call) RunAndReturn(run func() string) *Configer_GetAddressAccrual_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecretKey provides a mock function with given fields:
func (_m *Configer) GetSecretKey() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Configer_GetSecretKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretKey'
type Configer_GetSecretKey_Call struct {
	*mock.Call
}

// GetSecretKey is a helper method to define mock.On call
func (_e *Configer_Expecter) GetSecretKey() *Configer_GetSecretKey_Call {
	return &Configer_GetSecretKey_Call{Call: _e.mock.On("GetSecretKey")}
}

func (_c *Configer_GetSecretKey_Call) Run(run func()) *Configer_GetSecretKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Configer_GetSecretKey_Call) Return(_a0 string) *Configer_GetSecretKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Configer_GetSecretKey_Call) RunAndReturn(run func() string) *Configer_GetSecretKey_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewConfiger interface {
	mock.TestingT
	Cleanup(func())
}

// NewConfiger creates a new instance of Configer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewConfiger(t mockConstructorTestingTNewConfiger) *Configer {
	mock := &Configer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
